const subReddits = [
  "360 Video",
  "Accidental Comedy",
  "Artisan Videos",
  "Awful Commercials",
  "Best Of Liveleak",
  "Commercial Cuts",
  "Fast Workers",
  "Fucking With Nature",
  "IMGXXXX",
  "Obscure Media",
  "Premature Celebration",
  "Public Freakout",
  "RoadCam",
  "The Way We Were On Video",
  "Unexpected Thug Life",
  "Am I Being Detained",
  "Contagious Laughter",
  "Cooking Videos",
  "Cringe",
  "Curious Videos",
  "Deep Into YouTube",
  "Documentaries",
  "Educative Videos",
  "Fight Porn",
  "Full Movies On YouTube",
  "Full TV Shows On You Tube",
  "Happy Crowds",
  "Idiots Fighting Things",
  "Lectures",
  "Meal Time Videos",
  "Motivation Videos",
  "Play It Again Sam",
  "Street Fights",
  "Sweet Justice",
  "Trailers",
  "Video Porn",
  "Videos",
  "Vids",
  "Vines",
  "Virtual Freakout",
  "WoahTube",
  "Youtube Haiku"
]

export default subReddits